services:
  - type: web
    name: express-time-app
    runtime: docker
    buildCommand: |
      if [ -f package-lock.json ]; then 
        npm ci --only=production; 
      else 
        npm install --only=production; 
      fi
    startCommand: node index.js
    port: 10000
